@startuml
class Main{
    エントリーポイント
}

class Game{
    //ゲームに関することを書く
    SDLを初期化()
    ゲームループ()
    キー入力()
    描画()
    プレイデータ読み込み()
    ゲーム終了処理()
}

class Block{
    //ブロックの処理を書く
    ブロックの状態
    配置()
    各ブロックの状態。あるか無いか()
}

class Ball{
    //ボールの処理を書く
    色
    半径
    移動速度
    移動方向
    ボール配置()
}

class Bar{
    //バーの処理を書く
    幅
    高さ
    色
    移動速度
    初期位置
    バー配置()
}

class Stage{
    //ステージ管理
    ステージデータ読み込み()
    ステージクリア判定()
}

class Player{
    //プレイヤー管理
    残りプレイ回数処理()
}

class Sound{
    //BGM管理
    BGM読み込み()
    BGM再生()
    BGM停止()
}

class SoundEffect{
    //効果音管理
    効果音読み込み()
    効果音再生()
}

@enduml